In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

# Let's define a one-dimensional array 
import numpy as np

list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
print(list_1)

[50, 60, 80, 100, 200, 300, 500, 600]

In [45]:
# Let's create a numpy array from the list "my_list"
np_array  = np.array(list_1) 
print(np_array)
print(type(np_array))

[ 50  60  80 100 200 300 500 600]
<class 'numpy.ndarray'>

In [46]:
my_np_array = np.array(list_1)
print(my_np_array)
print(type(my_np_array))

[ 50  60  80 100 200 300 500 600]
<class 'numpy.ndarray'>

In [49]:
# Multi-dimensional (Matrix definition) 
matrix = np.random.randint(1,15,(5,5))
print(matrix)

[[ 1  8  3 14 10]
 [12  9  1  7 14]
 [ 2  2 14 13 13]
 [ 5 10 13  8  1]
 [ 8  9  9  7  2]]

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [52]:
multi_d_array = np.array([
    [3, 4, 9, 3 ],
    [4, 3, 2, 2]
])
print(multi_d_array)

[[3 4 9 3]
 [4 3 2 2]]

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS

In [54]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(10)
print(x)

[0.89824168 0.37706801 0.15672916 0.52867798 0.41123486 0.89643461
 0.52040715 0.63006255 0.63246654 0.29965331]

In [7]:
# you can create a matrix of random number as well
x = np.random.rand(3,3)
x

array([[0.79245992, 0.88399912, 0.20575804],
       [0.18632654, 0.99416866, 0.1400697 ],
       [0.37708331, 0.51520598, 0.0902322 ]])

In [57]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1,50)
x

42

In [9]:
# "randint" can be used to generate a certain number of random itegers as follows

x = np.random.randint(1,10,15)
x

array([1, 5, 8, 6, 4, 5, 7, 8, 2, 9, 7, 9, 3, 7, 3], dtype=int32)

In [10]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,31,2)
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [11]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [12]:
# Matrix of ones
x = np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# Array of zeros


x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [14]:
while True:
    x = int(input("Enter number freater than 0: "))
    if x > 0:
        break
    else:
        continue

random_nums =  np.random.randint(1,x,10)
random_nums

array([ 1,  8, 11,  3,  5,  3,  5, 11, 10,  8], dtype=int32)

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [15]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
y = np.arange(1,10)

In [17]:
# Add 2 numpy arrays together
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
sqrt = np.sqrt(squared)
print("Converted the numbers back again in their normal form")
sqrt

Converted the numbers back again in their normal form

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [21]:
x = [5, 7, 20]
x = np.array(x)
y = [9, 15, 4]
y = np.array(y)

distance = np.sqrt(np.sum((x - y)**2))
distance

np.float64(18.33030277982336)

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING

In [22]:
x = np.random

In [23]:
# Access specific index from the numpy array
x = np.array([1,2,3,4,5])

print(x[-1])

5

In [24]:
# Starting from the first index 0 up until and NOT including the last element
slice = x[0:3]
print(slice)

[1 2 3]

In [25]:
# Broadcasting, altering several values in a numpy array at once
y = x*5
z = x+5
x[0:3] = 7
print("Broadcatasted x: ",x)
print("Array + 5: ",z)
print("Array * 5: ", y)

Broadcatasted x:  [7 7 7 4 5]
Array + 5:  [ 6  7  8  9 10]
Array * 5:  [ 5 10 15 20 25]

In [26]:
# Let's define a two dimensional numpy array

matrix = np.random.randint(0,9,(4,3))

matrix

array([[8, 5, 4],
       [2, 0, 8],
       [1, 4, 2],
       [3, 7, 8]], dtype=int32)

In [27]:
# Get a row from a mtrix

first_row = matrix[0]
print(first_row) # First row
print(matrix[1]) # Second row

[8 5 4]
[2 0 8]

In [28]:
# Get one element

one_elm = matrix[0][0]
print("First element: ",one_elm)

First element:  8

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [29]:
matrix_1 = np.array([
    
        [2, 30, 20, -2, -4],
        [3, 4,  40, -3, -2],
        [-3, 4, -6, 90, 10],
        [25, 45, 34, 22, 12],
        [13, 24, 22, 32, 37]
])
matrix_1[4] = 0   
matrix_1

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [30]:
matrix = np.random.randint(1,10,(5,5))
matrix

array([[8, 7, 8, 9, 9],
       [9, 3, 9, 6, 1],
       [2, 9, 7, 4, 6],
       [3, 4, 1, 4, 6],
       [3, 9, 5, 9, 7]], dtype=int32)

In [31]:
greater_5 = matrix[matrix>7]
greater_5

array([8, 8, 9, 9, 9, 9, 9, 9, 9], dtype=int32)

In [32]:
# Obtain odd elements only
odd = matrix[matrix %2 != 0]
print(odd)

# Obtain even elements only
even = matrix[matrix %2 == 0]
even

[7 9 9 9 3 9 1 9 7 3 1 3 9 5 9 7]

array([8, 8, 6, 2, 4, 6, 4, 4, 6], dtype=int32)

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [33]:
my_array = np.array([
    [2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]
])

my_array[my_array < 0] = 0

my_array[my_array%2 == 1] = -2


my_array

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [34]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [35]:
import pandas as pd

In [36]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                              'Bank Clinet Name': ['Chanel','Steve','Mitch','Ryan'],
                              'Net Worth': [3500, 29000, 10000, 2000],
                              'Years with bank': [3, 4, 9, 5]}
                             )
bank_client_df

   Bank Client ID Bank Clinet Name  Net Worth  Years with bank
0             111           Chanel       3500                3
1             222            Steve      29000                4
2             333            Mitch      10000                9
3             444             Ryan       2000                5

In [37]:
# Let's obtain the data type 

print(type(bank_client_df))

<class 'pandas.DataFrame'>

In [58]:
# you can only view the first couple of rows using .head()

bank_client_df.head(2)

   Bank Client ID Bank Clinet Name  Net Worth  Years with bank
0             111           Chanel       3500                3
1             222            Steve      29000                4

In [39]:
# you can only view the last couple of rows using .tail()

bank_client_df.tail(2)

   Bank Client ID Bank Clinet Name  Net Worth  Years with bank
2             333            Mitch      10000                9
3             444             Ryan       2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [40]:
porfolio_pd = pd.DataFrame({
    'Stock Tickeer Symbol': ['AAPL', 'AMZN', 'T'],
    'Price per share': [3500, 200, 40],
    'Number of stocks': [3, 9, 4]
})

In [60]:
porfolio_pd

  Stock Tickeer Symbol  Price per share  Number of stocks
0                 AAPL             3500                 3
1                 AMZN              200                 9
2                    T               40                 4

In [61]:

stocks_dollar_value = porfolio_pd['Price per share']* porfolio_pd['Number of stocks']
stocks_dollar_value.sum()

np.int64(12460)

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [63]:
# Pandas is used to read a csv file and store data in a DataFrame
house_price_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')

ImportError: `Import lxml` failed.  Use pip or conda to install the lxml package.

In [ ]:
# Read tabular data using read_html

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

# TASK #8: PANDAS OPERATIONS

In [ ]:
# Let's define a dataframe as follows:

In [ ]:
# Pick certain rows that satisfy a certain criteria

In [ ]:
# Delete a column from a DataFrame

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

# TASK #9: PANDAS WITH FUNCTIONS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

In [ ]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake)

In [ ]:
# You can apply a function to the DataFrame

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

In [ ]:
# You can sort the values in the dataframe according to number of years with bank

In [ ]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True

In [ ]:
# Set inplace = True to ensure that change has taken place in memory

In [ ]:
# Note that now the change (ordering) took place

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

In [ ]:
X[4] = 0
X

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200

In [ ]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

In [ ]:
results.sum()

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df